### ISSUE TITLE
Client cert was not validated

### ISSUE THREAD

**Issue by duj4** [safing/tlsauth#1]
Dear author,

I am trying to use this plugin in my Traefik for authenticating client cert and here is my configuration:
static.yml:
```
experimental:
  localPlugins:
    tlsauth:
      moduleName: tlsauth
```
Plugin loaded successfully:
![image](https://github.com/safing/tlsauth/assets/19278537/4eaab76f-b38e-4f05-97f8-d33cb0a7becf)

dynamic.yml:
```
http:
  middlewares:
    tlsauth:
      plugin:
        tlsauth:
          # usernameHeader: "User"
          users:
            a: b
```
The CN and SAN in my lab is for "centos8-1", but I set the key/value pair in users as "a:b", it should block the access? As the expected CN/SAN should be a. However, when I tried to curl the site, it is still valid:
```
[dujas@centos8-1 tls]$ curl https://centos8-1:8443 --cacert ca.crt --cert centos8-1.crt --key centos8-1.key
<a href="/dashboard/">Found</a>.
```

Did I missing something?

Thanks.
